# Generated by Django 4.1 on 2024-05-20 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0002_lobby_created_at_lobby_deleted_at_lobby_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('9061967b-1b5a-4542-85e4-35b5abfcee98'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='00f7710c265640edafb87cfa92335be9', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('528eb2e5-7074-40c9-84e3-e550ea9e6a2a'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='724b05c3ef2949efac5c6f4c92bb2b27', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='ba69916d66874a38a7fe8ae4b051aed4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('fc4473af-be2c-4cbe-8e4a-c291725ef7e8'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='6c077160e18d4e09a44d5b08c8a549b2', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='7bbb827e04374956a44fe9401727ac80', max_length=191, primary_key=True, serialize=False),
        ),
    ]
