# Generated by Django 4.1 on 2024-05-20 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0005_alter_bill_id_alter_customer_id_alter_foodorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('8e050aa6-8bb2-4fb8-879a-f621d2843a7f'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='7d7fdc57aba04c5894790ead7cbc63e2', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('f044eb05-30a1-4199-9995-01683c8785cd'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='94284ff37a2f4bca96ec38c8858f8084', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='9b1df882bf804a42a737f571e516e783', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('1ff0cc00-c93e-4e2a-b9a0-a7326d1c1626'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='c2ba1e77b5cb45d792c2e9e061e53d75', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='127acb090fb146afb59e6c0f57c212b8', max_length=191, primary_key=True, serialize=False),
        ),
    ]
