# Generated by Django 4.1 on 2024-05-20 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0006_alter_bill_id_alter_customer_id_alter_foodorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('11816828-2923-420b-ae86-e31188095d6b'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='03e03f8eeda74f838cfb49c2e525151b', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('410afb84-8aa8-4fdb-852c-fcf7c9b637d6'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='7e54cfb290204558997056eca6a762a1', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='7d67b252456b4be59743cfc3c7027eb6', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('3942caf8-6a5e-4580-bba3-acae80333f44'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='b913fe4b6ae942cfa7d7d6d6a3131318', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='bcc8f7f2fa074deab692c3d2bb8f68d5', max_length=191, primary_key=True, serialize=False),
        ),
    ]
