# Generated by Django 4.1 on 2024-05-20 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0007_alter_bill_id_alter_customer_id_alter_foodorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('b2997d14-a131-4ba2-b78c-c5552213e14f'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='df31f17a208d49c98be53eb229ab88c3', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('c2ef28b4-d092-4f0a-9287-3a30c564c20c'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='f426d28a931745b9a3997fc97a093cee', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='3c40716c2a28435fa5ee9ba03103a791', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('ba8efd42-94cf-46af-90a5-b3e1b9a4547a'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='506517f9f15a46a4a2d980a14e036ba4', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='4ca200782df34f2abc615021a600473d', max_length=191, primary_key=True, serialize=False),
        ),
    ]
