# Generated by Django 4.1 on 2024-05-20 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0008_alter_bill_id_alter_customer_id_alter_foodorder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('4a07972e-72cd-4068-8373-427d23bd737d'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='7d621c679f0d42c7bb89ee45ef2230f1', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('fc55aae4-1cc1-4543-87aa-d077193e4967'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='67ad46c8193a4d3396e7db4c4d0ef15a', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='5617d37f1c514a5fa3ac09255f776c9b', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('25aef02f-85b8-4826-8187-50d5f1e69709'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='d7a3f54faf434b3f9dddf236755de65c', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='aa7c6775a4854db8aa90ee405335d996', max_length=191, primary_key=True, serialize=False),
        ),
    ]
