# Generated by Django 4.1 on 2024-05-20 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0009_remove_lobby_deleted_at_alter_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('888afacb-c270-4bcf-ae63-4251c770e4b9'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='a020f01629e3404f93f06af97a1c21b3', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('7f5a6e68-1e28-498c-9f7a-ef2001708756'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='3887afbe68604958af783b6e90f67c80', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='2ace479de6344524a6c0f782930cbf55', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('132a5393-773a-406d-ab7d-d1666084dadc'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='c75e220fc2044b58a918def134f1fb82', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='844c61e7d893497e823135e8f02c824b', max_length=191, primary_key=True, serialize=False),
        ),
    ]
