# Generated by Django 4.1 on 2024-05-20 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0010_lobby_deleted_at_alter_bill_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('371475b3-354a-46bf-bf8b-3a295c8458f1'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='862f471ed5fd4a20b24eafe83217cc48', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('c8688f43-bb8c-4f3f-88ca-15ed9004b747'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='deleted_at',
            field=models.CharField(default='null', max_length=191),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='609e2567b70e4e2ca97a540f1ffc42a0', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='deleted_at',
            field=models.CharField(max_length=191, null='null'),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='ce127ac0de9a4b1e9590148af06b1356', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('f27fb04e-b5ff-4def-b832-1ada577eaa66'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='deleted_at',
            field=models.CharField(default='null', max_length=191),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='d8fe863d2e1c45fe9d6426391912db90', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='274ddc01dcad4c7ea3f09f4d4a21855e', max_length=191, primary_key=True, serialize=False),
        ),
    ]
