# Generated by Django 4.1 on 2024-05-20 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('All_models', '0011_alter_bill_id_alter_customer_id_alter_foodorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(default=uuid.UUID('901770d4-9d37-4d44-805f-78dd72204298'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='4dd18843321b4caf8181f47ab8ab6907', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='id',
            field=models.CharField(default=uuid.UUID('d9ececd8-a708-4346-b910-64a0581872c8'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='74a6402437494894bb5a3981b0330c76', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='deleted_at',
            field=models.CharField(default='null', max_length=191),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='c764ae566bdd46ad8e238e856d790d5f', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.CharField(default=uuid.UUID('b9b7544c-869b-473c-bde1-ff4d8373bdc6'), max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.CharField(default='9026b0f473a94312960c4edb2bf41e24', max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.CharField(default='bfc106005cc54575afac0af6fc934cef', max_length=191, primary_key=True, serialize=False),
        ),
    ]
