# Generated by Django 4.1 on 2024-05-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LobType',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('max_table_count', models.IntegerField()),
                ('min_table_count', models.IntegerField()),
                ('deposit_percent', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'LobType',
            },
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('lob_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lobby.lobtype')),
            ],
            options={
                'db_table': 'Lobby',
            },
        ),
    ]
