# Generated by Django 4.1 on 2024-05-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobtype',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lobtype',
            old_name='min_table_count',
            new_name='min_table_price',
        ),
        migrations.RenameField(
            model_name='lobtype',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
