# Generated by Django 4.1 on 2024-05-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0002_rename_create_at_lobtype_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='lob_type_id',
            new_name='lob_type',
        ),
    ]
