# Generated by Django 4.1 on 2024-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0003_rename_lob_type_id_lobby_lob_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobtype',
            name='delete_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
