# Generated by Django 4.1 on 2024-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0004_lobtype_delete_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobtype',
            name='delete_at',
        ),
        migrations.AddField(
            model_name='lobtype',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
