# Generated by Django 4.1 on 2024-05-19 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0005_remove_lobtype_delete_at_lobtype_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9009c9f4-f4a4-4718-b7ea-655f96fb4f17'), editable=False, primary_key=True, serialize=False),
        ),
    ]
