# Generated by Django 4.1 on 2024-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0006_alter_lobtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='deddc653d5084583ade255e7fb10090b', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
