# Generated by Django 4.1 on 2024-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0007_alter_lobtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='7a031a7fd85d4ae2ae37e99e1d74f5a8', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
