# Generated by Django 4.1 on 2024-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0008_alter_lobtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.CharField(default='7324e7b78b964e9a82594c8ef6a526c7', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lobtype',
            name='id',
            field=models.CharField(default='b34ba0cd741e4265a7f513efd96b7b54', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
