# Generated by Django 4.1 on 2024-05-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0009_alter_lobby_id_alter_lobtype_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='LobType',
        ),
    ]
