# Generated by Django 4.1 on 2024-05-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_rename_role_id_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
