# Generated by Django 4.1 on 2024-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_alter_role_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
